---
- hosts: "all"
  become: yes
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_only: yes

    - name: Install required packages
      dnf:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
